{% set name = "lazyimread" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lyehe/lazyimread/archive/v{{ version }}.tar.gz
  sha256: 6527ffc72b98d018e5af11ea57b66852bee4b3ad4aea16e7d183117c2286c1db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - numpy
    - opencv
    - tifffile
    - h5py
    - zarr
    - xmltodict
    - pyyaml

test:
  imports:
    - lazyimread
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lyehe/lazyimread
  summary: A lazy image reading library for various file formats
  description: |
    Lazyimread is a Python library that simplifies working with large, 
    multi-dimensional image datasets. It can handle importing of various 
    image file formats such as TIFF, HDF5, Zarr, image sequences, and 
    video files without writing boilerplate code for each format.
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lyehe
